#! /bin/sh

## Autostart (statusbar)
$HOME/.config/polybar/launch.sh &
#yabar &
#excalibar &

## Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

## Bspwm configuration
bspc config border_width          2
bspc config window_gap            10
bspc config top_padding           30
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

## Bspwm rules
bspc rule -a firefox desktop='^2'
bspc rule -a KeePassXC desktop='^6'
bspc rule -a onboard state=floating
